# Generated by Django 2.1.7 on 2022-04-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='Ebook',
        ),
    ]
