# Generated by Django 4.0.1 on 2022-04-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_auto_20220421_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='quty',
            new_name='qynt',
        ),
    ]
